# Generated by Django 3.1.7 on 2021-03-19 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=255, verbose_name='文件名')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srcip', models.CharField(blank=True, default='', max_length=40, verbose_name='源IP')),
                ('dstip', models.CharField(blank=True, default='', max_length=40, verbose_name='目标IP')),
                ('layer_level', models.CharField(blank=True, default='', max_length=16, verbose_name='网络层次')),
                ('proto_name', models.CharField(blank=True, default='', max_length=16, verbose_name='网络协议')),
                ('ttl', models.IntegerField(blank=True, default=0, verbose_name='生存时间')),
                ('version', models.IntegerField(blank=True, default=0, verbose_name='版本')),
                ('srcmac', models.CharField(blank=True, default='', max_length=18, verbose_name='源mac')),
                ('dstmac', models.CharField(blank=True, default='', max_length=18, verbose_name='目的mac')),
                ('content', models.CharField(default='', max_length=1024, verbose_name='协议内容')),
                ('fileid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.capfile')),
            ],
        ),
    ]
