# Generated by Django 3.1.7 on 2021-03-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='hop',
            field=models.IntegerField(null=True, verbose_name='距离抓包机器时的跳数'),
        ),
    ]
