# Generated by Django 3.1.7 on 2021-03-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_data_hop'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sniff_time',
            field=models.DateTimeField(null=True, verbose_name='嗅探时间'),
        ),
    ]
