# Generated by Django 3.1.7 on 2021-03-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_data_sniff_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='ind',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
